### ISSUE TITLE
permissions fixes needed

### ISSUE THREAD

**Issue by hexylena** [erasche/chado-schema-builder#10]
About a year ago they "fixed" the postgres container where any init scripts are now run as postgres instead of root. *Grumbles*

https://github.com/docker-library/postgres/blame/master/9.5/docker-entrypoint.sh#L47
https://github.com/docker-library/postgres/commit/3706d4c4562c284ed070286b9fd516151167a40c#diff-a73bfefa953d89e708fbc5a158ec16eb

just fyi @abretaud. Updating the image because I'm setting up build.usegalaxy.eu to build this.

**Comment by abretaud** [comment]
Aaaaah, I understand better why I had to do https://github.com/erasche/docker-chado/pull/7 
Very cool for build.usegalaxy.eu!

**Comment by hexylena** [comment]
Ah, yeah, that does explain that :( How annoying.

**Comment by hexylena** [comment]
And sourceforge broke our http requests :(

```
wget --quiet 'http://song.cvs.sourceforge.net/*checkout*/song/ontology/so.obo'
```

no longer works.

**Comment by hexylena** [comment]
oh, even better, they've moved to github

https://github.com/The-Sequence-Ontology/SO-Ontologies/

**Comment by abretaud** [comment]
Is it passing with this github link?

Maybe with https://github.com/galaxy-genome-annotation/python-chado/pull/3 we could test new builds to make sure they work (I have some gff loading code (and tests!) nearly ready to push in this PR)

**Comment by hexylena** [comment]
definitely! would love to have that testing. It's still building... :( gosh I forgot how long it takes. https://build.usegalaxy.eu/job/usegalaxy.eu/job/chado-schema-builder/12/console

**Comment by hexylena** [comment]
Our cloud died. I'll try re-building tomorrow.

**Comment by abretaud** [comment]
Poor cloud, RIP! No problem

**Comment by hexylena** [comment]
https://build.usegalaxy.eu/job/usegalaxy.eu/job/chado-schema-builder/17/

It works!!

**Comment by abretaud** [comment]
Wouhou super cool! Thanks @erasche!
