### ISSUE TITLE
Jenkins not running?

### ISSUE THREAD

**Issue by abretaud** [erasche/chado-schema-builder#12]
Hi!
I just saw that there hasn't been a new build for https://build.galaxyproject.eu/job/usegalaxy-eu/job/chado-schema-builder/ since gcc, I thought it was supposed to run +/- each month, maybe a trigger doesn't work somewhere?
No hurry at all though, I'm happy with current dump

**Comment by hexylena** [comment]
yeaaaa I don't know what happened but there wasn't a build trigger on cron. Ok fixed :) Next build sept 3.

> Would last have run at Saturday, August 3, 2019 1:40:33 PM CEST; would next run at Tuesday, September 3, 2019 1:40:33 PM CEST.

**Comment by abretaud** [comment]
Cool, thanks!
