### ISSUE TITLE
Missing SOFP

### ISSUE THREAD

**Issue by hexylena** [erasche/chado-schema-builder#7]
```
# gmod_load_cvterms.pl -s SOFP load/etc/feature_property.obo
WARNING: If your databse is already populated with cvterms, not running in UPDATE mode (option -u) may cause database conflicts, such as violating unique constraints!
Default for -s: SOFP (specifies the database names for Dbxref objects)
Default for -F: File format set to obo
Connected to database postgres on host localhost.
Parsing the ontology load/etc/feature_property.obo...
Default namespace is feature_property 
....found namespace  'feature_property' 
cv_id = 14
Updating an ontology in the database...
Ontology name: feature_property
Getting all the terms of the new ontology...
***found 6 predicate terms!.
Retrieved 0 terms.
predicate term 'IS_A' already exists with cv_id 4
predicate term 'PART_OF' already exists with cv_id 4
Predicate term RELATED_TO will be stored later if used as a relationship in an ontology term
predicate term 'REGULATES' already exists with cv_id 4
predicate term 'POSITIVELY_REGULATES' already exists with cv_id 4
predicate term 'NEGATIVELY_REGULATES' already exists with cv_id 4
Getting all the terms of the current ontology...
Indexing terms and relationships...
Determining which terms are new...
Determine which terms are not in the file anymore...
 
                      These terms will be set to obsolete in the database
Inserting and updating terms...
Updated 0 existing terms, inserted 0 new terms!
Parsing out the relationships...
Looking at relationships in file.

Looking at relationships in database.
Relationships not in the file...

feature_property : 0 novel relationships among 0 were found and stored.
Committing! 
 If you are using cvtermpath you should now run gmod_make_cvtermpath.pl . See the perldoc for more info. 
```

**Comment by hexylena** [comment]
This results in missing `Note` and a bunch of other FP terms.

**Comment by hexylena** [comment]
cc @abretaud

**Comment by abretaud** [comment]
Damn! I secretly hoped I wouldn't ever need to look at this ontology loading code :)
I'll have a look

**Comment by hexylena** [comment]
Hah, I'd hoped the same, it's terrifying :/

Once we get this issue fixed, I'll add the yeast loading as part of the testing to ensure the schemas are functional, since we've been lacking test cases.

Thanks for having taking a look, really appreciate it!

**Comment by abretaud** [comment]
It looks like gmod_load_cvterms.pl doesn't load the [Typedef] stuff in the db.
For me the problem was hidden by tripal: it loads the feature_property during its installation if it's not already there
I'm looking into the gmod_load_cvterms.pl code to see what goes wrong... to be continued

**Comment by abretaud** [comment]
Some progress (writing here before I forget):
- gmod_load_cvterms.pl does load [Typedef], but only when they are used in the same obo file (which is not the case for feature_property)
- stag-storenode.pl (which is called when running make ontologies) properly loads them
- we stopped using `make ontologies` for most ontologies because it caused some `duplicate key violation` errors
-other ontologies also have some Typedef which are not loaded because they are not used in the same obo, here's list:


```
never_in_taxon
starts_during
developmentally_preceded_by
isolated_from_germplasm
associated_with
complete_evidence_for_feature
connects_on
contained_by
disconnected_from
edited_from
edited_to
evidence_for_feature
exemplar_of
finished_by
finishes
gained
genome_of
guides
has_integral_part
homologous_to
integral_part_of
is_consecutive_sequence_of
lost
maximally_overlaps
orthologous_to
paralogous_to
partial_evidence_for_feature
position_of
processed_from
processed_into
recombined_from
recombined_to
sequence_of
similar_to
started_by
starts
trans_spliced_from
trans_spliced_to
translates_to
translation_of
TAXRANK:1000000
```

(and the ugly command to get this:

```for t in `grep -A 1 Typedef /build/*obo | grep -v Typedef | grep -v "\--" | cut -f2 -d' '`; do grep $t /build/*obo | grep -q "relationship:"; echo $t$?; done | grep 1```

)

The simplest is probably to load SOFP with make ontologies instead of gmod_load_cvterms.pl: should work, but does not fix the problem with other terms from the list above (don't know if it could have any impact for anyone)...

**Comment by hexylena** [comment]
Fixed, you're awesome @abretaud, I owe you one.

**Comment by abretaud** [comment]
No problem, I'll need this too quite soon :)
Just tested with tripal, it looks ok there too
